import { WarehousePanelComponent } from './warehouse-panel';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { AppPageHeader } from '../../shared/ui/page-header';
import { RecordFormComponent, FormField } from '../../shared/ui/record-form';
import { HasPermission } from '../../shared/directives/has-permission';
import { NotificationService } from '../../core/services/notification.service';
import { AuthStateService } from '../../core/auth/auth-state.service';
import { SettingsApiService } from './settings-api.service';
@Component({selector:'app-settings-page',imports:[ReactiveFormsModule,MatButtonModule,AppPageHeader,RecordFormComponent,HasPermission,WarehousePanelComponent],template:'<app-page-header title="Configuración" subtitle="Tu negocio, a tu manera." /><form class="card" [formGroup]="form" (ngSubmit)="save()"><h2>Identidad de la empresa</h2><p>El nombre y el logo aparecerán en las nuevas facturas y presupuestos.</p><div class="logo-upload">@if(logo()){<img [src]="logo()" alt="Logo de la empresa" />}<label *hasPermission="\'settings.manage\'">{{uploading()?"Cargando logo…":"Cargar logo (PNG o JPG, máximo 2 MB)"}}<input type="file" accept="image/png,image/jpeg" [disabled]="uploading()" (change)="uploadLogo($event)" /></label></div><h2>Empresa y preferencias</h2><app-record-form [form]="form" [fields]="fields" /><div class="form-actions"><button mat-flat-button *hasPermission="\'settings.manage\'" [disabled]="form.invalid||saving()">Guardar configuración</button></div></form><app-warehouse-panel *hasPermission="\'inventory.view\'" />'})
export class SettingsPageComponent {
 readonly logo=signal<string|null>(null);readonly uploading=signal(false);
 uploadLogo(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;if(file.size>2097152||!["image/png","image/jpeg"].includes(file.type)){this.notifications.error("Selecciona una imagen PNG o JPG de hasta 2 MB.");input.value="";return;}this.uploading.set(true);this.api.uploadLogo(file).subscribe({next:r=>{this.logo.set(r.logo);this.uploading.set(false);input.value="";this.notifications.success("Logo guardado");},error:()=>{this.uploading.set(false);input.value="";}});}
 private readonly api=inject(SettingsApiService);private readonly state=inject(AuthStateService);private readonly notifications=inject(NotificationService);readonly saving=signal(false);
 readonly form=inject(FormBuilder).nonNullable.group({name:['',Validators.required],legalName:['',Validators.maxLength(500)],taxId:['',Validators.maxLength(500)],phone:['',Validators.maxLength(500)],email:['',[Validators.email,Validators.maxLength(500)]],address:['',Validators.maxLength(500)],invoiceAdditionalInfo:['',Validators.maxLength(1000)],invoiceLogoScale:[1,[Validators.min(.25),Validators.max(2.5)]],currency:['DOP',Validators.required],country:['DO',Validators.required],timeZone:['America/Santo_Domingo',Validators.required],allowNegativeStock:[false],allowDuplicateSaleItems:[false],defaultTaxRate:[0,[Validators.min(0),Validators.max(100)]],quoteExpirationDays:[30,[Validators.min(1),Validators.max(365)]],invoicePrefix:['FAC',Validators.required],quotePrefix:['COT',Validators.required]});
 readonly fields:FormField[]=[{key:'name',label:'Nombre del negocio'},{key:'legalName',label:'Razón social'},{key:'taxId',label:'Identificación fiscal'},{key:'phone',label:'Teléfono'},{key:'email',label:'Email',type:'email'},{key:'address',label:'Dirección'},{key:'invoiceAdditionalInfo',label:'Información adicional para factura',type:'textarea'},{key:'invoiceLogoScale',label:'Escala del logo en PDF',type:'number'},{key:'currency',label:'Moneda (ISO)'},{key:'country',label:'País (ISO)'},{key:'timeZone',label:'Zona horaria'},{key:'defaultTaxRate',label:'Impuesto predeterminado (%)',type:'number'},{key:'quoteExpirationDays',label:'Vigencia del presupuesto (días)',type:'number'},{key:'invoicePrefix',label:'Prefijo de ventas'},{key:'quotePrefix',label:'Prefijo de presupuestos'},{key:'allowNegativeStock',label:'Permitir stock negativo',type:'checkbox'},{key:'allowDuplicateSaleItems',label:'Permitir productos duplicados en ventas',type:'checkbox'}];
 constructor(){this.api.get().subscribe(r=>{this.logo.set(r.logo);this.form.patchValue({...r.settings,...r.business,legalName:r.business.legalName??'',taxId:r.business.taxId??'',phone:r.business.phone??'',email:r.business.email??'',address:r.business.address??'',invoiceAdditionalInfo:r.settings.invoiceAdditionalInfo??'',invoiceLogoScale:r.settings.invoiceLogoScale??1,allowDuplicateSaleItems:r.settings.allowDuplicateSaleItems??false});if(!this.state.has('settings.manage'))this.form.disable();});}
 save(){if(this.form.invalid)return;this.saving.set(true);this.api.save(this.form.getRawValue()).subscribe({next:r=>{this.saving.set(false);this.state.session.update(s=>s?{...s,business:r.business}:null);this.notifications.success('Configuración guardada');},error:()=>this.saving.set(false)});}
}
